[build]
  functions = "functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ioredis", "pg", "pg-pool"]

[dev]
  framework = "#static"
  publish = "."
  port = 8888
  targetPort = 8888
  command = "npm start"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 