[build]
  command = "npm run build"
  functions = "functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18.x"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ioredis", "pg", "pg-pool"]
  included_files = ["functions/config/redis.js", "functions/config/postgres.js"]

[dev]
  framework = "#static"
  publish = "."
  port = 8888
  targetPort = 8888

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 