[build]
  functions = "functions"
  publish = "."

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["ioredis"]
  included_files = ["functions/config/redis.js"]

[dev]
  framework = "#static"
  targetPort = 8888
  edge_functions = false

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 